package Screens;


import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class HocalarEkrani extends javax.swing.JFrame {

    /**
     * Creates new form HocalarEkranı
     */
    public HocalarEkrani() {
        initComponents();
        setLocationRelativeTo(null);
       hocalarList.addListSelectionListener(new ListSelectionListener() {

    public void valueChanged(ListSelectionEvent e) {
       

      if(hocalarList.getSelectedValue().toString().equals("FİTNESS EĞİTMENİ")){

       jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/suphan.jpg")));
       bilgiArea.setText("*Süphan YAKUT \n *22 Yaşında \n *Fitness eğitmenliğinin yanı sıra Gazi Üniversitesi Bilgisayar Mühendisliği Öğrencisi \n *Maaşı:2000 TL \n *Tecrübesi 2 Yıl \n");

    }else if(hocalarList.getSelectedValue().toString().equals("YÜZME EĞİTMENİ")){

       jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/umut.jpg")));
       bilgiArea.setText("*Umut ARPAY\n *22 Yaşında \n *Yüzme eğitmenliğinin yanı sıra Gazi Üniversitesi Bilgisayar Mühendisliği Öğrencisi \n *Maaşı:3000 TL \n *Tecrübesi 1.5 Yıl \n");


}else if(hocalarList.getSelectedValue().toString().equals("BOKS EĞİTMENİ")){

       jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cenkhoca.jpg")));
       bilgiArea.setText("*Cenk HOCA\n *42 Yaşında \n *Boks eğitmeni ve eski vücut geliştirme şampiyonu\n *Maaşı:8000 TL \n *Tecrübesi 15 Yıl \n");

 }else if(hocalarList.getSelectedValue().toString().equals("PLATES EĞİTMENİ")){

       jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/handansarıkaya.jpg")));
       bilgiArea.setText("*Handen SARIKAYA\n *36 Yaşında \n*Plates eğitmeni \n *Maaşı:5000 TL \n *Tecrübesi 7 Yıl \n");

 }
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        hocalarList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bilgiArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hocalarList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "FİTNESS EĞİTMENİ", "YÜZME EĞİTMENİ", "BOKS EĞİTMENİ", "PLATES EĞİTMENİ" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        hocalarList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(hocalarList);

        bilgiArea.setEditable(false);
        bilgiArea.setColumns(20);
        bilgiArea.setRows(5);
        jScrollPane2.setViewportView(bilgiArea);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel2.setText(" EĞİTMENLERİMİZ");

        backBtn.setText("GERİ");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(backBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
     AnaMenu anaMenu = new AnaMenu();
     this.setVisible(false); 
     anaMenu.setVisible(true);
     

    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HocalarEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HocalarEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HocalarEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HocalarEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HocalarEkrani().setVisible(true);
            }
        });
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextArea bilgiArea;
    private javax.swing.JList<String> hocalarList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
