/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens;

import Entities.Uye;
import Operations.DatabaseIslemleri;
import Operations.YuzmeOperations;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


public class YüzmeEkrani extends javax.swing.JFrame {

    DatabaseIslemleri dbIslemleri = new DatabaseIslemleri();
    YuzmeOperations yuzmeOperations = new YuzmeOperations();
    Timer timer;
    int min, sec;
    String minut = "";
    String second = "";
    boolean control = true;

    /**
     * Creates new form YüzmeEkrani
     */
    public YüzmeEkrani() {
        initComponents();

        setLocationRelativeTo(null);

        ArrayList<Uye> uyeList = dbIslemleri.uyeleriGetir();
        int counter = 0;
        for (Uye uye : uyeList) {
            if (uye.getBrans().equals("Yüzme")) {
                lbxYüzme.add(uye.getAd() + " " + uye.getSoyad());
                counter++;
            }

        }

        //mevcudu bulmak
        mevcutTxt.setText(String.valueOf(counter));

        //combobox elementleri doldurmak...
        //min
        for (int i = 0; i < 60; i++) {
            if (i < 10) {
                cbxMin.addItem(String.valueOf("0" + i));

            } else {
                cbxMin.addItem(String.valueOf(i));
            }

        }
        //sec
        for (int i = 0; i < 60; i++) {
            if (i < 10) {
                cbxSec.addItem(String.valueOf("0" + i));

            } else {
                cbxSec.addItem(String.valueOf(i));
            }

        }

        
            if (lbxYüzenÜyeler.getItemCount() == 0) {
                 uyeHavuzCikarBtn.setEnabled(false);
            }

        }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        lbxYüzme = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();
        mevcutTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        uyeHavuzGirisBtn = new javax.swing.JButton();
        uyeHavuzCikarBtn = new javax.swing.JButton();
        geriBtn = new javax.swing.JButton();
        cbxMin = new javax.swing.JComboBox<>();
        cbxSec = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        lbxSüresiDolan = new java.awt.List();
        lbxYüzenÜyeler = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("YÜZME");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("ŞU AN YÜZEN ÜYELER");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("MEVCUT:");

        mevcutTxt.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("YÜZME ÜYE LİSTESİ");

        uyeHavuzGirisBtn.setText("ÜYE GİRİŞİ YAP");
        uyeHavuzGirisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyeHavuzGirisBtnActionPerformed(evt);
            }
        });

        uyeHavuzCikarBtn.setText("ÜYE ÇIKAR");
        uyeHavuzCikarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyeHavuzCikarBtnActionPerformed(evt);
            }
        });

        geriBtn.setText("GERİ");
        geriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriBtnActionPerformed(evt);
            }
        });

        cbxMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMinActionPerformed(evt);
            }
        });

        cbxSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSecActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("SÜRESİ DOLAN ÜYELER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mevcutTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbxYüzme, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uyeHavuzGirisBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbxYüzenÜyeler, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(157, 157, 157))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(cbxMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(176, 176, 176)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbxSüresiDolan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(158, 158, 158))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(geriBtn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(uyeHavuzCikarBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jLabel10)
                    .addContainerGap(811, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(geriBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(uyeHavuzGirisBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbxYüzenÜyeler, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbxSüresiDolan, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(uyeHavuzCikarBtn)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(mevcutTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lbxYüzme, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(jLabel10)
                    .addContainerGap(482, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriBtnActionPerformed

        AnaMenu anaMenu = new AnaMenu();
        anaMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_geriBtnActionPerformed

    private void uyeHavuzGirisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyeHavuzGirisBtnActionPerformed

        String girisYapan = lbxYüzme.getSelectedItem();

        lbxYüzenÜyeler.add(girisYapan);

        uyeHavuzCikarBtn.setEnabled(true);

        sayacBaslat(girisYapan);

    }//GEN-LAST:event_uyeHavuzGirisBtnActionPerformed

    private void cbxMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMinActionPerformed
        minut = cbxMin.getSelectedItem().toString();
        //lblMin.setText(minut);
        min = Integer.parseInt(minut);
    }//GEN-LAST:event_cbxMinActionPerformed

    private void cbxSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSecActionPerformed
        second = cbxSec.getSelectedItem().toString();
        //lblSec.setText(second);
        sec = Integer.parseInt(second);
    }//GEN-LAST:event_cbxSecActionPerformed

    private void uyeHavuzCikarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyeHavuzCikarBtnActionPerformed
        
        lbxSüresiDolan.remove(lbxYüzenÜyeler.getSelectedItem());
        lbxYüzenÜyeler.remove(lbxYüzenÜyeler.getSelectedItem());

        if(lbxYüzenÜyeler.getItemCount()==0){
        uyeHavuzCikarBtn.setEnabled(false);
}

    }//GEN-LAST:event_uyeHavuzCikarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YüzmeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YüzmeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YüzmeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YüzmeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YüzmeEkrani().setVisible(true);
            }
        });
    }

    public void sayacBaslat(String girisYapan) {
        //sayac ıslemi..."

        timer = new Timer(1000, new ActionListener() {

            int sec = Integer.parseInt(cbxSec.getSelectedItem().toString());

            public void actionPerformed(ActionEvent e) {

                sec--;
                if (sec == 0) {
                    JOptionPane.showMessageDialog(rootPane, girisYapan + " Süre doldu", "Stopped", 0);
                    lbxSüresiDolan.add(girisYapan);

                }

                /*if (sec < 0) {
                    timer.stop();
                }*/
//                if (sec == 0) {
//                    sec = 60;
//                    min--;
//                }
//                if (min < 0) {
//                    JOptionPane.showMessageDialog(rootPane, girisYapan + " Süre doldu", "Stopped", 0);
//                    lbxSüresiDolan.add(girisYapan);
//
//                    minut = cbxMin.getSelectedItem().toString();
//                   
//                    min = Integer.parseInt(minut);
//                    second = cbxSec.getSelectedItem().toString();
//                   
//                    sec = Integer.parseInt(second);
//                    timer.stop();
//                } else {
//                    sec--;
//
//                }
            }
        });

        timer.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxMin;
    private javax.swing.JComboBox<String> cbxSec;
    private javax.swing.JButton geriBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.List lbxSüresiDolan;
    private java.awt.List lbxYüzenÜyeler;
    private java.awt.List lbxYüzme;
    private javax.swing.JTextField mevcutTxt;
    private javax.swing.JButton uyeHavuzCikarBtn;
    private javax.swing.JButton uyeHavuzGirisBtn;
    // End of variables declaration//GEN-END:variables
}
